# 1. Usamos una imagen ligera de Python
FROM python:3.11-slim

# 2. Creamos una carpeta de trabajo dentro del contenedor
#WORKDIR /app

# 3. Copiamos el archivo de librerías
#COPY requirements.txt .

# 4. Instalamos las librerías
#RUN pip install --no-cache-dir -r requirements.txt

# 5. Copiamos todo el código del backend (incluyendo el modelo .joblib)
#COPY . .

# 6. Exponemos el puerto que usa Flask
#EXPOSE 5000

# 7. Comando para arrancar la app
#CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:create_app()"]